# Generated by Django 2.1.5 on 2019-02-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.CharField(max_length=2000, verbose_name='News content (html allowed)')),
                ('image', models.ImageField(blank=True, upload_to='news', verbose_name='News image')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
