# Generated by Django 2.1.5 on 2019-02-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full name')),
                ('more', models.CharField(max_length=200, verbose_name='Additional info')),
            ],
            options={
                'verbose_name_plural': 'Alumni',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Course title')),
                ('starts', models.DateTimeField(verbose_name='Starting date')),
                ('ends', models.DateTimeField(blank=True, null=True, verbose_name='Ending date')),
                ('old', models.BooleanField(default=True, verbose_name='Show date')),
                ('people', models.CharField(max_length=200, verbose_name='Speaker and/or organizers')),
                ('about', models.CharField(max_length=5000, verbose_name='More information (place etc., html allowed)')),
                ('bold', models.BooleanField()),
                ('image', models.ImageField(blank=True, upload_to='research', verbose_name='Graphic')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='External link (start with http://...)')),
                ('event_type', models.CharField(choices=[('MRUC', 'MR User Club'), ('LABM', 'Lab Meeting'), ('LOPN', 'Lab Opening')], default='LABM', max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='photos', verbose_name='foto')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('authors', models.CharField(max_length=400, verbose_name='Authors (html allowed)')),
                ('published', models.DateField(blank=True, null=True, verbose_name='Publication date (leave empty if not published)')),
                ('about', models.CharField(blank=True, max_length=2000, verbose_name='More information (html allowed)')),
                ('bold', models.BooleanField()),
                ('image', models.ImageField(blank=True, upload_to='research', verbose_name='Graphic')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='External link (start with http://...)')),
            ],
            options={
                'verbose_name_plural': 'Publications',
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('investigator', models.CharField(max_length=200, verbose_name='Principal Investigator')),
                ('institution', models.CharField(max_length=200, verbose_name='Institution name (lab)')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority (the more the higher at page)')),
                ('about', models.CharField(blank=True, max_length=5000, verbose_name='More information (html allowed)')),
                ('bold', models.BooleanField()),
                ('image', models.ImageField(blank=True, upload_to='research', verbose_name='Graphic')),
                ('about_image', models.CharField(blank=True, max_length=500, verbose_name='Image caption')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='External link (start with http://...)')),
                ('web', models.CharField(blank=True, max_length=500, verbose_name='Frame content (start with http://...)')),
                ('research_type', models.CharField(choices=[('NRI', 'Neuroimaging'), ('BHV', 'Behavioral')], default='NRI', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Research',
            },
        ),
    ]
