# Generated by Django 2.1.5 on 2019-02-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190227_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='priority',
            field=models.IntegerField(default=-1, verbose_name='Priority (the more the higher at page)'),
        ),
    ]
