# Generated by Django 2.2.1 on 2019-06-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190227_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.CharField(blank=True, max_length=32, verbose_name='GitHub username'),
        ),
        migrations.AddField(
            model_name='profile',
            name='orcid',
            field=models.CharField(blank=True, help_text='0000-0000-0000-0000', max_length=32, verbose_name='Orcid ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='scholar',
            field=models.CharField(blank=True, help_text='Enter just the ID. This is part of an url, e.g. https://scholar.google.pl/citations?user=<strong>qTDPssQAAAAJ</strong>&hl=pl', max_length=32, verbose_name='Google scholar ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='about',
            field=models.TextField(max_length=5000, verbose_name='More information (place etc., html allowed)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(max_length=2000, verbose_name='News content (html allowed)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=2000, verbose_name='About (html allowed)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='funding',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Funding (html allowed)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='publications',
            field=models.TextField(blank=True, max_length=12000, verbose_name='Selected publications (html allowed)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='research',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Research interests (html allowed)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='about',
            field=models.TextField(blank=True, max_length=2000, verbose_name='More information (html allowed)'),
        ),
        migrations.AlterField(
            model_name='research',
            name='about',
            field=models.TextField(blank=True, max_length=5000, verbose_name='More information (html allowed)'),
        ),
        migrations.AlterField(
            model_name='research',
            name='about_image',
            field=models.TextField(blank=True, max_length=500, verbose_name='Image caption'),
        ),
    ]
