# Generated by Django 2.2.1 on 2019-06-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190604_0920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Meeting',
        ),
    ]
