# Generated by Django 2.2.1 on 2019-06-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190612_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name_plural': 'Meetings'},
        ),
        migrations.AlterField(
            model_name='meeting',
            name='event_type',
            field=models.CharField(choices=[('SM', 'Seminar'), ('WS', 'Workshop')], default='SM', max_length=4),
        ),
    ]
