# Generated by Django 2.2.1 on 2019-06-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190612_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(max_length=2000, verbose_name='News content (html allowed)')),
                ('image', models.ImageField(blank=True, upload_to='news', verbose_name='News image')),
                ('event_type', models.CharField(choices=[('MD', 'Media release'), ('EV', 'Public event')], default='MD', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Public',
            },
        ),
        migrations.AlterField(
            model_name='meeting',
            name='event_type',
            field=models.CharField(choices=[('SM', 'Seminar'), ('WS', 'Workshop')], default='SM', max_length=2),
        ),
    ]
