# Generated by Django 2.2.1 on 2019-06-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190612_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos', verbose_name='Image file'),
        ),
    ]
