# Generated by Django 2.2.1 on 2019-06-13 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190613_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='starts',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Starting date'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='published',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Publication date (leave empty if not published)'),
        ),
    ]
