# Generated by Django 2.2.1 on 2019-06-13 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190613_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='published',
            field=models.DateField(blank=True, default=datetime.datetime.now, help_text='Leave empty if not published yet', null=True, verbose_name='Publication date'),
        ),
    ]
