# Generated by Django 2.2.1 on 2019-06-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190613_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='job',
            field=models.FileField(blank=True, upload_to='documents', verbose_name='Upload job anouncment (delete if closed)'),
        ),
        migrations.AddField(
            model_name='research',
            name='recruitment',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link to recruitment page (start with http://...)'),
        ),
    ]
