# Generated by Django 2.2.1 on 2019-07-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20190626_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='room',
            field=models.CharField(blank=True, max_length=200, verbose_name='Room/Place'),
        ),
    ]
