# Generated by Django 2.2.4 on 2019-10-25 18:05

from django.db import migrations, models
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_meeting_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='researchgate',
            field=models.CharField(blank=True, help_text='Enter just the ID (last part of URL), usually Name_Surname', max_length=32, validators=[home.validators.validate_researchgate], verbose_name='Researchgate profile ID'),
        ),
    ]
