# Generated by Django 2.2.1 on 2020-03-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20191230_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Alias')),
                ('slug', models.SlugField(default='', editable=False, max_length=500)),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='External link')),
            ],
            options={
                'verbose_name_plural': 'Aliases',
            },
        ),
    ]
